version: '3'

services:
  app:
    image: docker.io/library/stream-16-demo-app:0.0.2-SNAPSHOT
    ports:
      - '8899:8080'
    environment:
      APP_S3_BUCKET: 'new-super-bucket'

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - "./docker/prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    volumes:
      - "./docker/grafana.ini:/etc/grafana/grafana.ini"
      - "./docker/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml"
    ports:
      - "3000:3000"
    links:
      - prometheus
